### ISSUE TITLE
About run_training.sh 

### ISSUE THREAD

**Issue by MrWeiminlee** [wentaozhu/DeepLung#65]
I want to know the code of  run_training.sh 

 CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 64 --resume 064.ckpt --save-dir res18/retrft96$f/ --epochs $maxeps --config config_training$f

What '--config config_training9'   really means,I cannot find config_training9 in your project, so I think it could be config_training which is used for prepare.py, so I changed the code to '--config config_training', but I got error:
~/DeepLung-master$ sh run_training.sh

THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=88 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "main.py", line 387, in <module>
    main()
  File "main.py", line 65, in main
    torch.cuda.set_device(0)
  File "/home/weiminle/.conda/envs/Deeplung/lib/python2.7/site-packages/torch/cuda/__init__.py", line 244, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:88

So,about the config_training,did I do the right thing,and how can I solve the problem above?

**Comment by wentaozhu** [comment]
no CUDA-capable device. How many GPUs do you have?  You may need to change CUDA_VISIBLE_DEVICES=2,3,4,5,6,7

**Comment by MrWeiminlee** [comment]
> no CUDA-capable device. How many GPUs do you have? You may need to change CUDA_VISIBLE_DEVICES=2,3,4,5,6,7

**Comment by MrWeiminlee** [comment]
> no CUDA-capable device. How many GPUs do you have? You may need to change CUDA_VISIBLE_DEVICES=2,3,4,5,6,7

I changed the CUDA_VISIBLE_DEVICES and it works.Thanks a lot !
