### ISSUE TITLE
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered 

### ISSUE THREAD

**Issue by yqjaoshuang** [wentaozhu/DeepLung#8]
Dear Zhu,
when run run_training.sh, I encountered this error, and I have no idea how to deal with it. Could you give me some advice?
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCStorage.cu line=58 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "main.py", line 389, in <module>
    main()
  File "main.py", line 206, in main
    train(train_loader, net, loss, epoch, optimizer, get_lr, args.save_freq, save_dir)
  File "main.py", line 224, in train
    output = net(data, coord)
  File "/home/qyan0710/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/share/qyan0710/work/DeepLung/detector/res18.py", line 97, in forward
    out = self.preBlock(x)#16
  File "/home/qyan0710/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qyan0710/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/qyan0710/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qyan0710/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 388, in forward
    self.padding, self.dilation, self.groups)
  File "/home/qyan0710/software/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 126, in conv3d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCStorage.cu:58

**Comment by wentaozhu** [comment]
I think it is pytorch issue because you can find many this kind of issues if search by google. Try to update your cuda version into 9.1, reinstall the pytorch. During the running, keep monitoring your GPU usage by "nvidia-smi".

**Comment by yqjaoshuang** [comment]
It has been solved by decreasing the value of batch size. Thank you. And I close this comment now.

**Comment by t2ac32** [comment]
Would you say it was a memory issue?

**Comment by wentaozhu** [comment]
Try to update pytorch, cuda, cudnn and lower the batch size.
